In [1]:
import pandas as pd

In [2]:
headers = pd.read_csv('headers_daily01.txt', sep = ' ', header = 0)

In [3]:
headers = headers.T
headers = headers[:-1]
headers_list = headers.iloc[:,0]

In [4]:
headers_list

1                      WBANNO
2                    LST_DATE
3                      CRX_VN
4                   LONGITUDE
5                    LATITUDE
6                 T_DAILY_MAX
7                 T_DAILY_MIN
8                T_DAILY_MEAN
9                 T_DAILY_AVG
10               P_DAILY_CALC
11              SOLARAD_DAILY
12        SUR_TEMP_DAILY_TYPE
13         SUR_TEMP_DAILY_MAX
14         SUR_TEMP_DAILY_MIN
15         SUR_TEMP_DAILY_AVG
16               RH_DAILY_MAX
17               RH_DAILY_MIN
18               RH_DAILY_AVG
19      SOIL_MOISTURE_5_DAILY
20     SOIL_MOISTURE_10_DAILY
21     SOIL_MOISTURE_20_DAILY
22     SOIL_MOISTURE_50_DAILY
23    SOIL_MOISTURE_100_DAILY
24          SOIL_TEMP_5_DAILY
25         SOIL_TEMP_10_DAILY
26         SOIL_TEMP_20_DAILY
27         SOIL_TEMP_50_DAILY
28        SOIL_TEMP_100_DAILY
Name: 0, dtype: object

In [6]:
df = pd.DataFrame()
for year in range(2004, 2024):
    tmp = pd.read_csv('./CRND0103-202311060850/'+ str(year) + '/CRND0103-' + str(year) + '-NY_Ithaca_13_E.txt', delimiter= '\s+', header = None, na_values = [-99999, -9999,-99])
    df = pd.concat([df, tmp], axis = 0)
    
# from snapshots file CRND0103-202311060850.zip

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,64758,20041027,1.201,-76.25,42.44,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,64758,20041028,1.201,-76.25,42.44,12.7,-0.3,6.2,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64758,20041029,1.201,-76.25,42.44,16.3,2.5,9.4,9.7,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64758,20041030,1.201,-76.25,42.44,17.5,10.5,14.0,14.5,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,64758,20041031,1.201,-76.25,42.44,17.0,9.1,13.1,12.6,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,64758,20231101,2.622,-76.25,42.44,3.5,-2.2,0.6,0.2,3.0,...,0.352,0.328,0.329,0.364,0.021,7.0,7.7,8.7,10.0,11.6
305,64758,20231102,2.622,-76.25,42.44,6.1,-3.3,1.4,1.0,0.0,...,0.352,0.323,0.325,0.357,0.021,6.4,6.9,7.8,9.3,11.3
306,64758,20231103,2.622,-76.25,42.44,12.9,1.4,7.1,7.4,0.0,...,0.345,0.319,0.320,0.327,0.019,6.9,7.0,7.7,8.9,10.9
307,64758,20231104,2.622,-76.25,42.44,13.4,5.7,9.6,9.5,0.0,...,0.338,0.313,0.312,0.315,0.024,8.1,7.9,8.3,8.9,10.6
308,64758,20231105,2.622,-76.25,42.44,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns = headers_list

In [9]:
df

,WBANNO,LST_DATE,CRX_VN,LONGITUDE,LATITUDE,T_DAILY_MAX,T_DAILY_MIN,T_DAILY_MEAN,T_DAILY_AVG,P_DAILY_CALC,...,SOIL_MOISTURE_5_DAILY,SOIL_MOISTURE_10_DAILY,SOIL_MOISTURE_20_DAILY,SOIL_MOISTURE_50_DAILY,SOIL_MOISTURE_100_DAILY,SOIL_TEMP_5_DAILY,SOIL_TEMP_10_DAILY,SOIL_TEMP_20_DAILY,SOIL_TEMP_50_DAILY,SOIL_TEMP_100_DAILY
0,64758,20041027,1.201,-76.25,42.44,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,64758,20041028,1.201,-76.25,42.44,12.7,-0.3,6.2,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,64758,20041029,1.201,-76.25,42.44,16.3,2.5,9.4,9.7,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,64758,20041030,1.201,-76.25,42.44,17.5,10.5,14.0,14.5,1.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,64758,20041031,1.201,-76.25,42.44,17.0,9.1,13.1,12.6,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,64758,20231101,2.622,-76.25,42.44,3.5,-2.2,0.6,0.2,3.0,...,0.352,0.328,0.329,0.364,0.021,7.0,7.7,8.7,10.0,11.6
305,64758,20231102,2.622,-76.25,42.44,6.1,-3.3,1.4,1.0,0.0,...,0.352,0.323,0.325,0.357,0.021,6.4,6.9,7.8,9.3,11.3
306,64758,20231103,2.622,-76.25,42.44,12.9,1.4,7.1,7.4,0.0,...,0.345,0.319,0.320,0.327,0.019,6.9,7.0,7.7,8.9,10.9
307,64758,20231104,2.622,-76.25,42.44,13.4,5.7,9.6,9.5,0.0,...,0.338,0.313,0.312,0.315,0.024,8.1,7.9,8.3,8.9,10.6
308,64758,20231105,2.622,-76.25,42.44,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.isna().sum()

0
WBANNO                        0
LST_DATE                      0
CRX_VN                        0
LONGITUDE                     0
LATITUDE                      0
T_DAILY_MAX                  76
T_DAILY_MIN                  76
T_DAILY_MEAN                 76
T_DAILY_AVG                  77
P_DAILY_CALC                 47
SOLARAD_DAILY                56
SUR_TEMP_DAILY_TYPE           0
SUR_TEMP_DAILY_MAX          438
SUR_TEMP_DAILY_MIN          438
SUR_TEMP_DAILY_AVG           56
RH_DAILY_MAX               2405
RH_DAILY_MIN               2405
RH_DAILY_AVG               2405
SOIL_MOISTURE_5_DAILY      2933
SOIL_MOISTURE_10_DAILY     2820
SOIL_MOISTURE_20_DAILY     2539
SOIL_MOISTURE_50_DAILY     2456
SOIL_MOISTURE_100_DAILY    2456
SOIL_TEMP_5_DAILY          2456
SOIL_TEMP_10_DAILY         2456
SOIL_TEMP_20_DAILY         2456
SOIL_TEMP_50_DAILY         2456
SOIL_TEMP_100_DAILY        2456
dtype: int64

In [11]:
df.to_csv('daily01-NY_Ithaca_13_E.csv')